TOKEN = '804405572:AAGl597rNzL45nKTjd1FP5cBUSuWxirXQrU'
LATEST_POSTS_JSON_PATH = '../data_transfer/latest_posts.json'
LATEST_POSTS_XML_PATH = '../data_transfer/latest_posts.xml'
USERS_PATH = '../data_transfer/users.json'
ALL_TAGS_PATH = '../data_transfer/all_tags.txt'
XML_LINK = 'https://www.sports.ru/rss/rubric.xml?s=208'
